protected/models/Lokasi.php
<?php

/**
 * This is the model class for table "lokasi".
 *
 * The followings are the available columns in table 'lokasi':
 * @property integer $id
 * @property string $nama
 */
class Lokasi extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'lokasi';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nama', 'required'),
			array('nama', 'length', 'max'=>255),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, nama', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nama' => 'Nama',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('nama',$this->nama,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Lokasi the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public static function getLokasiStatis($id)
	{
		$model = Lokasi::model()->findByPk($id);
		if($model !==null)
			return $model->nama;
		else
			return null;
	}		

	public static function findAllLokasi()
	{
		return self::model()->findAll();
	}
}

protected/controllers/LokasiController.php
<?php

class LokasiController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

    /**
    * Specifies the access control rules.
    * This method is used by the 'accessControl' filter.
    * @return array access control rules
    */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','detail'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

    /**
    * Creates a new model.
    * If creation is successful, the browser will be redirected to the 'view' page.
    */
    public function actionCreate()
    {
        $model=new Lokasi;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Lokasi']))
        {
            $model->attributes=$_POST['Lokasi'];
        if($model->save())
            Yii::app()->user->setFlash('success','Data berhasil disimpan');
            $this->redirect(array('admin'));
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
    * Updates a particular model.
    * If update is successful, the browser will be redirected to the 'view' page.
    * @param integer $id the ID of the model to be updated
    */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['Lokasi']))
        {
            $model->attributes=$_POST['Lokasi'];

            if($model->save())
                $this->redirect(array('view','id'=>$model->id));
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    public function actionDetail($id)
    {
        $this->layout = '//layouts/column2';
    
        $this->render('detail',array(
            'model'=>$this->loadModel($id),         
        ));
    }

    /**
    * Deletes a particular model.
    * If deletion is successful, the browser will be redirected to the 'admin' page.
    * @param integer $id the ID of the model to be deleted
    */
    public function actionDelete($id)
    {
        if(Yii::app()->request->isPostRequest)
    {
    // we only allow deletion via POST request
    $this->loadModel($id)->delete();

    // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
    if(!isset($_GET['ajax']))
        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
    }
    else
        throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
    }

/**
* Lists all models.
*/
public function actionIndex()
{
    $this->layout = '//layouts/column2';
    // $dataProvider=new CActiveDataProvider('Lokasi');
    $model = new Lokasi();
    $this->render('index',array(
        'model'=>$model,
    ));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
$model=new Lokasi('search');
$model->unsetAttributes();  // clear any default values
if(isset($_GET['Lokasi']))
$model->attributes=$_GET['Lokasi'];

$this->render('admin',array(
'model'=>$model,
));
}

/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Lokasi::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='lokasi-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/controllers/StokController.php
<?php

class StokController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admin/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Stok;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_GET['id_lokasi']))
			$model->id_lokasi = $_GET['id_lokasi'];
		
		if(isset($_GET['id_komoditas']))
			$model->id_komoditas = $_GET['id_komoditas'];
		
		$model->tanggal = date('Y-m-d');
		if(isset($_GET['tanggal']))
			$model->tanggal = $_GET['tanggal'];

		


		if(isset($_POST['Stok']))
		{
			$model->attributes=$_POST['Stok'];			
			
			date_default_timezone_get('Asia/Jakarta');
            $model->waktu_dibuat = date('Y-m-d H:i:s');

			$model->stok = str_replace('.','', $model->stok);
			$lama = Stok::model()->findByAttributes(array(
						'id_komoditas'=>$model->id_komoditas,
						'id_lokasi'=>$model->id_lokasi,
						'tanggal'=>$model->tanggal
			));
			
			if($lama!==null)
			{
				$lama->stok = $model->stok;
				$lama->save();
			} else {
				$model->save();
			}
			
			Yii::app()->user->setFlash('success', 'Data stok berhasil disimpan');
			
			if (Yii::app()->controller->id == "lokasi") {
				$this->redirect(array('lokasi/admin'));
			}

			$this->redirect(array('komoditas/index'));

		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Stok']))
		{
			$model->attributes=$_POST['Stok'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Stok');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Stok('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Stok']))
			$model->attributes=$_GET['Stok'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Stok the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Stok::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Stok $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='stok-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/lokasi/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'lokasi-form',
	'type' => 'horizontal',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>
	
	<div class="well">
		<?php echo $form->textFieldGroup($model,'nama',array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-5'),
			'widgetOptions'=>array(
				'htmlOptions'=>array(
					'class'=>'span5','maxlength'=>255
		)))); ?>
	</div>

	<div class="form-actions well">
		<div class="row">
			<div class="col-sm-3">&nbsp;</div>
			<div class="col-sm-9">
				<?php $this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'submit',
					'context'=>'success',
					'icon'=>'ok',
					'label'=>'Simpan',
				)); ?>

				
				<?php $this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'link',
					'context'=>'success',
					'icon'=>'remove',
					'label'=>'Batal',
					'url'=>Yii::app()->request->Urlreferrer
				)); ?>
			</div>
		</div>
	</div>

<?php $this->endWidget(); ?>

protected/views/lokasi/_search.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

		<?php echo $form->textFieldGroup($model,'id',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5')))); ?>

		<?php echo $form->textFieldGroup($model,'nama',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>255)))); ?>

	<div class="form-actions">
		<?php $this->widget('booster.widgets.TbButton', array(
			'buttonType' => 'submit',
			'context'=>'primary',
			'label'=>'Search',
		)); ?>
	</div>

<?php $this->endWidget(); ?>

protected/views/lokasi/_view.php
<?php foreach($data->findAllSub() as $data) { ?>
<tr>
    <td><?php print $data->nama; ?>&nbsp;(<?php print $data->satuan; ?>)</td>    


    <?php if (Harga::getHarga($data->id,$model->id,$kemarinLusa) == Harga::getHarga($data->id,$model->id,$kemarin)) { ?>    
        <td style="text-align:right">
               <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$kemarinLusa)); ?>        
               <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>
        </td>
    <?php } else { ?>            
        <td style="text-align:right">
            <?php 
                $persen = Harga::getPersentaseHarga($data->id,$model->id,$kemarin);
                if ($persen < 0) {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/down.png').'&nbsp;';
                    print '('.Harga::getPersentaseHarga($data->id,$model->id,$kemarin).'%)';
                } else {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/up.png').'&nbsp;';
                    print '('.Harga::getPersentaseHarga($data->id,$model->id,$kemarin).'%)';
                }
            ?>                
            <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$kemarin)); ?>            
            <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>
        </td>
    <?php } ?>

    <?php if (Stok::getStok($data->id,$model->id,$kemarinLusa) == Stok::getStok($data->id,$model->id,$kemarin)) { ?>    
        <td style="text-align:right">                
               <?php print Helper::rp(Stok::getStok($data->id,$model->id,$kemarin)); ?>        
               <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
        </td>

    <?php } else { ?>            
        <td style="text-align:right">
            <?php 
                $persen = Stok::getPersentaseStok($data->id,$model->id,$kemarin);
                if ($persen < 0) {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/down.png').'&nbsp;';
                    print '('.Stok::getPersentaseStok($data->id,$model->id,$kemarin).'%)';
                } else {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/up.png').'&nbsp;';
                    print '('.Stok::getPersentaseStok($data->id,$model->id,$kemarin).'%)';
                }
            ?>                
            <?php print Helper::rp(Stok::getStok($data->id,$model->id,$kemarin)); ?>            
            <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
        </td>
    <?php } ?>

    <?php if (Harga::getHarga($data->id,$model->id,$kemarin) == Harga::getHarga($data->id,$model->id,$hariIni)) { ?>    
        <td style="text-align:right">                
               <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$kemarin)); ?>        
               <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>
        </td>

    <?php } else { ?>            
        <td style="text-align:right">
            <?php 
                $persen = Harga::getPersentaseHarga($data->id,$model->id,$kemarin);
                if ($persen < 0) {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/down.png').'&nbsp;';
                    print '('.Harga::getPersentaseHarga($data->id,$model->id,$kemarin).'%)';
                } else {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/up.png').'&nbsp;';
                    print '('.Harga::getPersentaseHarga($data->id,$model->id,$kemarin).'%)';
                }
            ?>                
            <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$kemarin)); ?>            
            <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>
        </td>
    <?php } ?>

    <?php if (Stok::getStok($data->id,$model->id,$kemarin) == Stok::getStok($data->id,$model->id,$hariIni)) { ?>    
        <td style="text-align:right">
               <?php print Helper::rp(Stok::getStok($data->id,$model->id,$kemarin)); ?>        
               <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
        </td>
    <?php } else { ?>            
        <td style="text-align:right">
            <?php 
                $persen = Stok::getPersentaseStok($data->id,$model->id,$hariIni);
                if ($persen < 0) {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/down.png').'&nbsp;';
                    print '('.Stok::getPersentaseStok($data->id,$model->id,$hariIni).'%)';
                } else {
                    print CHtml::image(Yii::app()->request->baseUrl.'/images/up.png').'&nbsp;';
                    print '('.Stok::getPersentaseStok($data->id,$model->id,$hariIni).'%)';
                }
            ?>                
            <?php print Helper::rp(Stok::getStok($data->id,$model->id,$hariIni)); ?>            
            <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
        </td>
    <?php } ?>

    


</tr>
<?php } ?>

protected/views/lokasi/admin.php
<?php
$this->breadcrumbs=array(
	'Lokasi'=>array('admin'),
	'Kelola',
);
?>

<h1>Kelola Lokasi</h1>

<?php $this->widget('booster.widgets.TbGridView',array(
		'id'=>'lokasi-grid',
		'type'=>'striped bordered condensed',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		'columns'=>array(
			'nama',
			array(
				'class'=>'booster.widgets.TbButtonColumn',				
			),
		),
)); ?>

<div>&nbsp;</div>

<div class="well" style="text-align:right">

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('lokasi/create'),
		'label'=>'Tambah Lokasi',
		'size'=>'small',
		'context'=>'success',
		'icon'=>'plus'
)); ?>&nbsp;

</div>

protected/views/lokasi/create.php
<?php
$this->breadcrumbs=array(
	'Lokasis'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Lokasi','url'=>array('index')),
array('label'=>'Manage Lokasi','url'=>array('admin')),
);
?>

<h1>Tambah Lokasi</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/lokasi/update.php
<?php
$this->breadcrumbs=array(
	'Lokasis'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

	$this->menu=array(
	array('label'=>'List Lokasi','url'=>array('index')),
	array('label'=>'Create Lokasi','url'=>array('create')),
	array('label'=>'View Lokasi','url'=>array('view','id'=>$model->id)),
	array('label'=>'Manage Lokasi','url'=>array('admin')),
	);
	?>

<h1>Sunting Lokasi</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/lokasi/view.php
<?php
$this->breadcrumbs=array(
	'Lokasi'=>array('admin'),
	'Kelola'	
);
?>

<?php
  
    $hariIni = date('Y-m-d');
    $kemarin = date( 'Y-m-d',strtotime('-1 days'));
    $kemarinLusa = date( 'Y-m-d',strtotime('-2 days'));

?>

<h1><?php print $model->nama ?></h1>

<div>&nbsp;</div>


<div class="well" style="text-align: right">
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('lokasi/update','id'=>$model->id),
		'label'=>'Sunting',
		'size'=>'small',
		'context'=>'success',
		'icon'=>'pencil'
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('lokasi/create'),
		'label'=>'Tambah',
		'size'=>'small',
		'context'=>'success',
		'icon'=>'plus'
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('lokasi/detail','id'=>$model->id),
		'label'=>'Lihat Lokasi',
		'size'=>'small',
		'context'=>'success',
		'icon'=>'search',
		'htmlOptions'=>array('target'=>'_blank')
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('lokasi/admin'),
		'label'=>'Kelola',
		'size'=>'small',
		'context'=>'success',
		'icon'=>'list'
)); ?>&nbsp;
</div>

<table class="table table-condensed table-hover" style="table-layout: fixed;">
	<thead>
		<tr>			
			<th rowspan="3" style="text-align: center;vertical-align:middle" width="30%">Komoditas</th>
			<th colspan="4" style="text-align: center">Perbandingan Harga Hari Ini</th>
		</tr>		
		<tr>
			<th colspan="2" style="text-align: center"><?php print Helper::getTanggalSingkat($kemarin); ?></th>
			<th colspan="2" style="text-align: center"><?php print Helper::getTanggalSingkat($hariIni); ?></th>
		</tr>
		<tr>
			<th style="text-align: center">Harga</th>
			<th style="text-align: center">Stok</th>
			<th style="text-align: center">Harga</th>
			<th style="text-align: center">Stok</th>
		</tr>	
	</thead>
	<?php $i=1; foreach(Komoditas::findAllKomoditasInduk() as $data) { ?>
	
	<tr>
		 <?php if(!$data->hasSub()) { ?>			 				 	
            <td><?php print $data->nama; ?></td>  
            <td style="width:20%;text-align:right">
                <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$kemarin)); ?>
                <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>                    
            </td>
            <td style='text-align:right'>
                <?php print Helper::rp(Stok::getStok($data->id,$model->id,$kemarin)); ?>                    
                <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$kemarin),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
            </td>

            <td style="width:20%;text-align:right">
                <?php print Helper::rp(Harga::getHarga($data->id,$model->id,$hariIni)); ?>                    
                <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>                    
            </td>
            
            <td style='text-align:right'>
                <?php print Helper::rp(Stok::getStok($data->id,$model->id,$hariIni)); ?>                    
                <?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('stok/create','id_lokasi'=>$model->id,'id_komoditas'=>$data->id,'tanggal'=>$hariIni),array('data-toggle'=>'tooltip','title'=>'Input Stok Baru')); ?>
            </td>                 
        <?php } ?>   



        <?php if($data->hasSub()) { ?>
            <?php $this->renderPartial('_view',array(
                    'data'=>$data,
                    'model'=>$model,
                    'hariIni'=>$hariIni,
                    'kemarin'=>$kemarin,
                    'kemarinLusa'=>$kemarinLusa
            )); ?>
        <?php } ?>              
	</tr>

	<?php $i++; } ?>   
</table>