protected/models/Harga.php
<?php

/**
 * This is the model class for table "Harga".
 *
 * The followings are the available columns in table 'Harga':
 * @property integer $id
 * @property integer $id_bahan_pokok
 * @property integer $id_lokasi
 * @property string $harga
 * @property string $tanggal_input
 */
class Harga extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'harga';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_komoditas, tanggal, id_lokasi, harga', 'required'),
			array('id_komoditas, id_lokasi ', 'numerical', 'integerOnly'=>true),
			array('harga', 'length', 'max'=>20),		
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, id_stok, id_komoditas, id_lokasi, harga, tanggal', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(			
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'id_komoditas' => 'Komoditas',
			'id_lokasi' => 'Lokasi',			
			'harga' => 'Harga',
			'tanggal' => 'Tanggal',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('id_komoditas',$this->id_komoditas);
		$criteria->compare('id_lokasi',$this->id_lokasi);		
		$criteria->compare('harga',$this->harga,true);
		$criteria->compare('tanggal',$this->tanggal,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	public function cari($id)
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		if(isset($_GET['Harga']))
			$this->attributes = $_GET['Harga'];

		$criteria=new CDbCriteria;


		$criteria->compare('id',$this->id);
		$criteria->compare('id_komoditas',$id);
		$criteria->compare('id_lokasi',$this->id_lokasi);		
		$criteria->compare('harga',$this->harga,true);
		$criteria->compare('tanggal',$this->tanggal,true);

		$criteria->order = 'tanggal DESC';

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}		

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Harga the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
	
	public static function getHarga($id_komoditas,$id_lokasi,$tanggal)
	{
		$criteria = new CDbCriteria;
		$criteria->condition = 'id_komoditas=:id_komoditas AND id_lokasi=:id_lokasi AND tanggal <= :tanggal';
		$criteria->params = array(
			':id_komoditas'=>$id_komoditas,
			':id_lokasi'=>$id_lokasi,
			':tanggal'=>$tanggal
		);
		$criteria->order='tanggal DESC';
			
		$model = Harga::model()->find($criteria);

		if($model!==null)
			return $model->harga;
		else
			return null;
	}
	
	public function getHargaRata($id_komoditas,$tanggal)
	{
		$komoditas = Komoditas::model()->findByPk($id_komoditas);
		
		if($komoditas->hasSub())
			return null;

		$hargaRata = 0;
		
		$i=0;
		
		$model = Lokasi::model()->findAll();
		
		$harga = 0;
		foreach($model as $lokasi)
		{
			$harga = $harga + $this->getHarga($id_komoditas,$lokasi->id,$tanggal);
			$i++;
		}
		
		if($i!=0)
			$hargaRata = $harga/$i;
		else
			$hargaRata = 0;
			
		return $hargaRata;
	}

	public static function getGrafik($id_lokasi,$id_komoditas)
	{
		$grafik = '';
		
		$bahan = Komoditas::model()->findByPk($id_komoditas);

		$tanggal_sekarang = date('Y-m-d');
		$tanggal = date( 'Y-m-d',strtotime("-30 days"));

		while($tanggal<=$tanggal_sekarang)
		{
			$grafik .= '{"label":"'.Helper::getTanggalChart($tanggal).'","value":"'.$bahan->getHarga($id_lokasi,$tanggal).'"},';		
			$tanggal = date('Y-m-d',strtotime($tanggal . "+1 days"));							
			
		} 

		return $grafik;
	}

	public function getPersentaseHarga($id_komoditas,$id_lokasi,$tanggal)
	{

		$komoditas = Komoditas::model()->findByPk($id_komoditas);
		$lokasi = Lokasi::model()->findByPk($id_lokasi);

		if($komoditas->hasSub())
			return null;

		$hariIni = $tanggal;
    	$kemarin = date( 'Y-m-d',strtotime('-1 days',strtotime($tanggal)));
			
		$hargaHariIni = Harga::model()->getHarga($id_komoditas,$id_lokasi,$hariIni);
		$hargaKemarin = Harga::model()->getHarga($id_komoditas,$id_lokasi,$kemarin);


		if ($hargaKemarin != null) {
			return round(($hargaHariIni-$hargaKemarin)/$hargaKemarin * 100,1);
		} else return null;

	}

	


	public function getNamaKomoditas()
	{
		$model = Komoditas::model()->findByPk($this->id_komoditas);
		if($model!==null) {
			return $model->nama;
		} else {
			return null;
		}
/*		$model = Komoditas::model()->findByPk($this->id_komoditas);

		if (Komoditas::model()->countByAttributes(array('id_induk'=>$this->id)) > 0) {
			return $model->nama;
		} else {
			return null;
		}*/
	}

	public function getNamaSatuan()
	{
		$model = Komoditas::model()->findByPk($this->id_komoditas);
		if($model !==null)
			return $model->satuan;
		else
			return null;
	}

	public function getNamaLokasi()
	{
		$model = Lokasi::model()->findByPk($this->id_lokasi);
		if($model !==null)
			return $model->nama;
		else
			return null;
	}	

	public function getRelation($relation,$field)
	{
		if(!empty($this->$relation->$field))
			return $this->$relation->$field;
		else
			return null;
	}	

	

	
}

protected/controllers/HargaController.php
<?php

class HargaController extends Controller
{
/**
* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
* using two-column layout. See 'protected/views/layouts/column2.php'.
*/
public $layout='//layouts/admin/column2';

/**
* @return array action filters
*/
public function filters()
{
return array(
'accessControl', // perform access control for CRUD operations
);
}

/**
* Specifies the access control rules.
* This method is used by the 'accessControl' filter.
* @return array access control rules
*/
public function accessRules()
{
return array(
		array('allow',  // allow all users to perform 'index' and 'view' actions
			'actions'=>array('index','view'),
			'users'=>array('*'),
		),
		array('allow', // allow authenticated user to perform 'create' and 'update' actions
			'actions'=>array('create','update','exportExcel'),
			'users'=>array('@'),
		),
		array('allow', // allow admin user to perform 'admin' and 'delete' actions
			'actions'=>array('admin','delete'),
			'users'=>array('admin'),
		),
		array('deny',  // deny all users
			'users'=>array('*'),
		),
);
}

/**
* Displays a particular model.
* @param integer $id the ID of the model to be displayed
*/
public function actionView($id)
{
$this->render('view',array(
'model'=>$this->loadModel($id),
));
}

/**
* Creates a new model.
* If creation is successful, the browser will be redirected to the 'view' page.
*/
	public function actionCreate()
	{
		$model=new Harga;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_GET['id_lokasi']))
			$model->id_lokasi = $_GET['id_lokasi'];
		
		if(isset($_GET['id_komoditas']))
			$model->id_komoditas = $_GET['id_komoditas'];
		
		$model->tanggal = date('Y-m-d');
		if(isset($_GET['tanggal']))
			$model->tanggal = $_GET['tanggal'];


		if(isset($_POST['Harga']))
		{
			$model->attributes=$_POST['Harga'];			
			
			date_default_timezone_get('Asia/Jakarta');
            $model->waktu_dibuat = date('Y-m-d H:i:s');

			$model->harga = str_replace('.','', $model->harga);
			$lama = Harga::model()->findByAttributes(array(
						'id_komoditas'=>$model->id_komoditas,
						'id_lokasi'=>$model->id_lokasi,
						'tanggal'=>$model->tanggal
			));
			
			if($lama!==null)
			{
				$lama->harga = $model->harga;
				$lama->save();
			} else {
				$model->save();
			}
			
			Yii::app()->user->setFlash('success', 'Data harga berhasil disimpan');

			if (Yii::app()->controller == "lokasi") {
				$this->redirect(array('lokasi/admin'));
			}

			$this->redirect(array('komoditas/index'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

/**
* Updates a particular model.
* If update is successful, the browser will be redirected to the 'view' page.
* @param integer $id the ID of the model to be updated
*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);
		$model->harga = number_format($model->harga,0,',','.');
		if(isset($_POST['Harga']))
		{
			$model->attributes=$_POST['Harga'];
			$model->harga = str_replace('.','', $model->harga);
			
			if($model->save())
			{
				Yii::app()->user->setFlash('success', 'Data harga berhasil disimpan');
				$this->redirect(array('komoditas/view','id'=>$model->id_komoditas));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

/**
* Deletes a particular model.
* If deletion is successful, the browser will be redirected to the 'admin' page.
* @param integer $id the ID of the model to be deleted
*/
public function actionDelete($id)
{
if(Yii::app()->request->isPostRequest)
{
// we only allow deletion via POST request
$this->loadModel($id)->delete();

// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
if(!isset($_GET['ajax']))
$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
}
else
throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
}

/**
* Lists all models.
*/
public function actionIndex()
{
$dataProvider=new CActiveDataProvider('Harga');
$this->render('index',array(
'dataProvider'=>$dataProvider,
));
}

/**
* Manages all models.
*/
public function actionAdmin()
{
	$model=new Harga('search');
	$model->unsetAttributes();  // clear any default values
	if(isset($_GET['Harga']))
	$model->attributes=$_GET['Harga'];

	$this->render('admin',array(
	'model'=>$model,
	));
}


	public function actionExportExcel($tanggal)
	{
		spl_autoload_unregister(array('YiiBase','autoload'));
		
		Yii::import('application.vendors.PHPExcel',true);
		
		spl_autoload_register(array('YiiBase', 'autoload'));

		$PHPExcel = new PHPExcel();
			
		$PHPExcel->getActiveSheet()->setCellValue('A1', 'DAFTAR ISIAN HARGA RATA - RATA BEBERAPA BAHAN POKOK PANGAN ');
		$PHPExcel->getActiveSheet()->setCellValue('A2', 'DAN BARANG STRATEGIS LAINNYA DI KABUPATEN BELITUNG TIMUR');
		$PHPExcel->getActiveSheet()->setCellValue('A3', 'PROVINSI KEPULAUAN BANGKA BELITUNG');
		$PHPExcel->getActiveSheet()->setCellValue('A4', strtoupper('Hari: '.Helper::getHari($tanggal).', '.Helper::tanggal($tanggal)));
		$PHPExcel->getActiveSheet()->getStyle('A1:A4')->getFont()->setBold(true);
		$PHPExcel->getActiveSheet()->getStyle('A1:A4')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

		$PHPExcel->getActiveSheet()->setCellValue('A8', 'NO');
		$PHPExcel->getActiveSheet()->setCellValue('B8', 'KOMODITI');
		$PHPExcel->getActiveSheet()->setCellValue('C8', 'SATUAN');
		$PHPExcel->getActiveSheet()->setCellValue('D8', 'LOKASI');
		$PHPExcel->getActiveSheet()->getStyle('A8:D8')->getFont()->setBold(true);

		$PHPExcel->getActiveSheet()->getColumnDimension('A')->setWidth(5);
		$PHPExcel->getActiveSheet()->getColumnDimension('B')->setWidth(35);
		$PHPExcel->getActiveSheet()->getColumnDimension('C')->setWidth(25);		
		$PHPExcel->getActiveSheet()->mergeCells('A8:A9');
		$PHPExcel->getActiveSheet()->mergeCells('B8:B9');
		$PHPExcel->getActiveSheet()->mergeCells('C8:C9');
		
		$ord = ord('C');
		
		foreach(Lokasi::model()->findAll() as $lokasi)
		{
			$ord++;
			
			$PHPExcel->getActiveSheet()->setCellValue(chr($ord).'9', strtoupper($lokasi->nama));
			$PHPExcel->getActiveSheet()->getStyle(chr($ord).'9')->getFont()->setBold(true);
			$PHPExcel->getActiveSheet()->getColumnDimension(chr($ord))->setWidth(35);
		}

		$PHPExcel->getActiveSheet()->mergeCells('D8:'.chr($ord).'8');

		$ord++;
		
		$PHPExcel->getActiveSheet()->setCellValue(chr($ord).'8', 'RATA');
		$PHPExcel->getActiveSheet()->getStyle(chr($ord).'8')->getFont()->setBold(true);
		$PHPExcel->getActiveSheet()->mergeCells(chr($ord).'8:'.chr($ord).'9');

		$PHPExcel->getActiveSheet()->mergeCells('A1:'.chr($ord).'1');
		$PHPExcel->getActiveSheet()->mergeCells('A2:'.chr($ord).'2');
		$PHPExcel->getActiveSheet()->mergeCells('A3:'.chr($ord).'3');
		$PHPExcel->getActiveSheet()->mergeCells('A4:'.chr($ord).'4');
			
		$i = 0;
		$kolom = 10;

		foreach(Komoditas::model()->findAllByAttributes(array('id_induk'=>null),array('order'=>'urutan ASC')) as $data)
		{
			
			$i++; $kolom++;

			$PHPExcel->getActiveSheet()->setCellValue('A'.$kolom, $i);
			$PHPExcel->getActiveSheet()->setCellValue('B'.$kolom, $data->nama);

			if(!$data->hasSub()) 
			{			
				$PHPExcel->getActiveSheet()->setCellValue('C'.$kolom,$data->satuan);
				$chr = ord('D');
				$dr = '';
				foreach(Lokasi::model()->findAll() as $lokasi)
				{
					$dr = $chr+1;
					$PHPExcel->getActiveSheet()->setCellValue(chr($chr).$kolom,$data->getHarga($lokasi->id,$tanggal));
					$PHPExcel->getActiveSheet()->setCellValue(chr($dr).$kolom,Harga::model()->getHargaRata($data->id,$tanggal));
					$chr++;
				}
			}

			if($data->hasSub()) 
			{
				foreach($data->getSub() as $subdata)
				{
					$kolom++;
					$PHPExcel->getActiveSheet()->setCellValue('B'.$kolom, '---'.$subdata->nama);
					$PHPExcel->getActiveSheet()->setCellValue('C'.$kolom, $subdata->satuan);

					$chr = ord('D');
					$dr = '';
					foreach(Lokasi::model()->findAll() as $lokasi)
					{
						$dr = $chr+1;
						$PHPExcel->getActiveSheet()->setCellValue(chr($chr).$kolom, $subdata->getHarga($lokasi->id,$tanggal));
						$PHPExcel->getActiveSheet()->setCellValue(chr($dr).$kolom,$subdata->getHargaRata($data->id,$tanggal));
						$chr++;
					}
				}
			} 	
		}	
		
		$PHPExcel->getActiveSheet()->getStyle('A8'.$kolom.':D'.$kolom)->getBorders()->getAllBorders()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);				
		
		$PHPExcel->getActiveSheet()->getStyle('A8:F9')->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	  	$PHPExcel->getActiveSheet()->getStyle('A11:A'.$kolom)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);
	  	$PHPExcel->getActiveSheet()->getStyle('C11:C'.$kolom)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER);

		$filename = time().'_HargaKomoditas.xlsx';

		$path = Yii::app()->basePath.'/../exports/';
		$objWriter = PHPExcel_IOFactory::createWriter($PHPExcel, 'Excel2007');
		$objWriter->save($path.$filename);	
		$this->redirect(Yii::app()->request->baseUrl.'/exports/'.$filename);

	}



/**
* Returns the data model based on the primary key given in the GET variable.
* If the data model is not found, an HTTP exception will be raised.
* @param integer the ID of the model to be loaded
*/
public function loadModel($id)
{
$model=Harga::model()->findByPk($id);
if($model===null)
throw new CHttpException(404,'The requested page does not exist.');
return $model;
}

/**
* Performs the AJAX validation.
* @param CModel the model to be validated
*/
protected function performAjaxValidation($model)
{
if(isset($_POST['ajax']) && $_POST['ajax']==='harga-form')
{
echo CActiveForm::validate($model);
Yii::app()->end();
}
}
}

protected/views/harga/_form.php
<?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
	'id'=>'harga-form',
	'type' => 'horizontal',
	'enableAjaxValidation'=>false,
)); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<div class="well">
	<?php echo $form->dropDownListGroup($model,'id_komoditas',array(
				'wrapperHtmlOptions'=>array('class'=>'col-sm-3'),
				'widgetOptions'=>array(
					'htmlOptions'=>array('empty'=>'-- Pilih Bahan Pokok --','disabled'=>'disabled'),
					'data'=>CHtml::listData(Komoditas::model()->findAll(),'id','nama')
				)
	)); ?>
	
	<?php echo $form->select2Group($model,'id_lokasi',array(
				'wrapperHtmlOptions'=>array('class'=>'col-sm-3'),
				'widgetOptions'=>array(
					'htmlOptions'=>array('empty'=>'-- Pilih Lokasi --'),
					'data'=>CHtml::listData(Lokasi::model()->findAll(),'id','nama')
				)
	)); ?>
	
	<?php echo $form->datePickerGroup($model,'tanggal',array(
				'wrapperHtmlOptions'=>array('class'=>'col-sm-3'),
				'widgetOptions'=>array(
					'options'=>array('format'=>'yyyy-mm-dd','autoclose'=>true),
					'htmlOptions'=>array('class'=>'span5')
				), 
				'prepend'=>'<i class="glyphicon glyphicon-calendar"></i>', 
	)); ?>

	<?php echo $form->textFieldGroup($model,'harga', array(
			'wrapperHtmlOptions'=>array('class'=>'col-sm-3'),
			'widgetOptions'=>array(
				'htmlOptions'=>array('rows'=>3,'class'=>'format-money')
			),
			'prepend'=>'Rp',
			'label'=>'Harga'
	)); ?>

</div>

	<div class="form-actions well">
		<div class="row">
			<div class="col-sm-3">&nbsp;</div>
			<div class="col-sm-9">
				<?php $this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'submit',
					'context'=>'success',
					'icon'=>'ok',
					'label'=>'Simpan',
				)); ?>

				
				<?php $this->widget('booster.widgets.TbButton', array(
					'buttonType'=>'link',
					'context'=>'success',
					'icon'=>'remove',
					'label'=>'Batal',
					'url'=>Yii::app()->request->Urlreferrer
				)); ?>
			</div>
		</div>
	</div>

<?php $this->endWidget(); ?>

protected/views/harga/_search.php
<?php

$this->widget('zii.widgets.jui.CJuiDatePicker', array(
    'name'=>'firstDate',
    'options'=>array('showAnim'=>'fold',
        'dateFormat'=>'yy/mm/dd',
    ),
    'htmlOptions'=>array(
        'style'=>'height:20px;',
    ),
));
?>

protected/views/harga/_tabel.php
<?php foreach($model as $data) { ?>
<tr>
	<td>&nbsp;</td>
	<td>
		<?php 
			$this->widget(
			    'booster.widgets.TbButtonGroup',
			    array(
			        'size' => 'small',
			        'context' => 'success',
			        'buttons' => array(
			            array(
			                'label' => '',
			                'items' => array(
											array('label' => 'Update Bahan', 'url' => array('komoditas/update','id'=>$data->id,'id_komoditas'=>$data->id)),	
											'---',	
											  array('label' => 'Naik Urutan', 'url' => array('komoditas/naikUrutan','id'=>$data->id)),
											   array('label' => 'Turun Urutan', 'url' => array('komoditas/turunUrutan','id'=>$data->id)),						
			                )
			            ),
			        ),
			    )
			); echo ' ';
		 ?>
		<?php print $data->nama; ?>

	</td>
	<td style="text-align:center"><?php print $data->satuan; ?></td>
	<?php foreach(Lokasi::model()->findAll() as $lokasi) { ?>
	<td style="text-align:right"><?php print number_format(Harga::model()->getHarga($data->id,$lokasi->id,$tanggal),0,',','.'); ?>
		<?php print CHtml::link("<i class='glyphicon glyphicon-pencil icon'></i>",array('harga/create','id_lokasi'=>$lokasi->id,'id_komoditas'=>$data->id),array('data-toggle'=>'tooltip','title'=>'Input Harga Baru')); ?>
	</td>
	<?php } ?>
	<?php if($data->hasSub()) { ?>
	<td>&nbsp;</td>
	<?php } else { ?>
	<td style="text-align:right"><?php print number_format(Harga::model()->getHargaRata($data->id,$tanggal),0,',','.'); ?></td>
	<?php } ?>
	
</tr>
<?php } ?>

protected/views/harga/_view.php
<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_komoditas')); ?>:</b>
	<?php echo CHtml::encode($data->id_komoditas); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('id_lokasi')); ?>:</b>
	<?php echo CHtml::encode($data->id_lokasi); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('harga')); ?>:</b>
	<?php echo CHtml::encode($data->harga); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tanggal')); ?>:</b>
	<?php echo CHtml::encode($data->tanggal); ?>
	<br />


</div>

protected/views/harga/admin.php
<?php
$this->breadcrumbs=array(
	'Hargas'=>array('index'),
	'Manage',
);

$this->menu=array(
array('label'=>'List Harga','url'=>array('index')),
array('label'=>'Create Harga','url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
$('.search-form').toggle();
return false;
});
$('.search-form form').submit(function(){
$.fn.yiiGridView.update('harga-grid', {
data: $(this).serialize()
});
return false;
});
");
?>

<h1>Manage Hargas</h1>

<p>
	You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
		&lt;&gt;</b>
	or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
	<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('booster.widgets.TbGridView',array(
'id'=>'harga-grid',
'dataProvider'=>$model->search(),
'filter'=>$model,
'columns'=>array(
		'id',
		'id_komoditas',
		'id_lokasi',
		'harga',
		'tanggal',
array(
'class'=>'booster.widgets.TbButtonColumn',
),
),
)); ?>

protected/views/harga/create.php
<?php
$this->breadcrumbs=array(
	'Hargas'=>array('index'),
	'Create',
);

$this->menu=array(
array('label'=>'List Harga','url'=>array('index')),
array('label'=>'Manage Harga','url'=>array('admin')),
);
?>

<h1>Tambah Harga</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/harga/update.php
<?php
$this->breadcrumbs=array(
	'Hargas'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);
?>

<h1>Sunting Harga</h1>

<?php echo $this->renderPartial('_form',array('model'=>$model)); ?>

protected/views/harga/view.php
<?php
$this->breadcrumbs=array(
	'Hargas'=>array('index'),
	$model->id,
);
?>

<h1>Lihat Harga</h1>

<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('update','id'=>$model->id),
		'label'=>'Sunting',
		'context'=>'primary',
		'icon'=>'pencil'
)); ?>&nbsp;
<?php $this->widget('booster.widgets.TbButton',array(
		'buttonType'=>'link',
		'url'=>array('create'),
		'label'=>'Tambah',
		'context'=>'primary',
		'icon'=>'plus'
)); ?>&nbsp;

<div>&nbsp;</div>

<?php $this->widget('booster.widgets.TbDetailView',array(
		'data'=>$model,
		'type'=>'striped bordered condensed',
		'attributes'=>array(
			'id',
			'id_bahan',
			'id_lokasi',
			'harga',
			'tanggal',
		),
)); ?>